# docker-compose.yml

version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: carlosgon  
      POSTGRES_USER: carlosgon
      POSTGRES_PASSWORD: carlos123


